[phases.setup]
nixPkgs = [
  'nodejs_20',
  '(python311.withPackages (ps: with ps; [ openpyxl lxml ]))'
]

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'